FROM node:latest
RUN yarn global add \
        nodemon \
        vue \
        @vue/cli \
        @vue/cli-init \
        @vue/cli-service-global

RUN yarn global add \
        axios \
        body-parse \
        mongodb \
        mongoose
        
WORKDIR /home
