FROM node:latest
RUN yarn global add \
        babel-core \
        babel-loader \
        babel-preset-react \
        babel-preset-es2015 \
        nodemon \
        vue \
        @vue/cli \
        @vue/cli-init \
        @vue/cli-service-global


RUN yarn global add \
        axios \
        body-parse \
        mongodb \
        mongoose
        
WORKDIR /home
