FROM node:latest
RUN yarn global add \
        babel-cli \
        nodemon \
        vue-cli \
        webpack


RUN yarn global add \
        axios \
        body-parse \
        mongodb \
        mongoose
        
WORKDIR /home
